
# resume information
resume-index = 3469387
seed = 12015186755714343875
rate = 1000      
shard = 1/1
nocapture = servername

output-filename = /home/cos/masscan_full_20260628.txt
output-format = list

adapter-ip = 192.168.1.3
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 1-65535
range = 192.168.1.0/24

